### ISSUE TITLE
The general package

### ISSUE THREAD

**Issue by lilyclements** [acircleda/footprint#10]
This looks like a really interesting package. I have a similar methodology for air emissions in a package [carbonr](https://github.com/IDEMSInternational/carbonr). The use of the latitude and longitude is a great addition that you have included! I notice you haven't updated the emissions since the 2019 report. I was wondering if this is still being actively used? Or, if you were interested in any level of collaboration?

Would be great to hear from you. 

Thanks.

**Comment by acircleda** [comment]
Hi. I'll take a look at your package. 
I have been meaning to update the GHG emissions and include an argument for year, but have not gotten the time to do so. So, for now, everything is based on 2019.

I'd be interested in collaboration. Contact me via email and we can discuss.
