### ISSUE TITLE
Emission calculation 

### ISSUE THREAD

**Issue by sgichuki** [acircleda/footprint#9]
I noticed differences in the results when one calculates emissions for flights individually versus using a tibble as shown in the package documentation. e.g. `airport_footprint("ORY", "AMS", "Business", "co2e")` [1] 110.365 ; `airport_footprint("CDG", "AMS", "Business", "co2e")`[1] 101.563. I had an idea to calculate the emissions from Paris to different cities e.g. Paris-London, Paris-Amsterdam etc. 

`travel_data <- tibble(name = c("Paris->London", 
                               "Paris->Amsterdam", 
                               "Paris->Frankfurt"),
                      from = c("CDG", "CDG", "CDG"),
                      to = c("LHR", "AMS", "FRA")) %>% #"LYS","BOD","NTE"))
mutate(emissions = airport_footprint(travel_data$from,travel_data$to,"Business","co2e"))

Each row in the resulting table shows 101.563. I am not sure if this is because these are airports within similar distance ranges or not. Using the `airport_footprint` function on its own results in different results for different itineraries, this is what made me wonder if there could be a problem somewhere. 

The following error also comes up when I try to add new destinations in the tibble e.g. Paris-Nantes with along with the respective ICAO airport codes: 
`<error/dplyr:::mutate_error>
Error in `mutate()`:
! Problem while computing `emissions = airport_footprint(...)`.
Caused by error in `airport_footprint()`:
! object 'travel_data' not found
---
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─dplyr:::mutate.data.frame(...)
  4. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  5. │   ├─base::withCallingHandlers(...)
  6. │   └─mask$eval_all_mutate(quo)
  7. ├─footprint::airport_footprint(...)
  8. └─base::.handleSimpleError(...)
  9.   └─dplyr h(simpleError(msg, call))
 10.     └─rlang::abort(...)`

**Comment by acircleda** [comment]
Hi! Since you are calculating across rows (from, to), you will need to add [`rowwise()`](https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-rowwise/) to your code. See below:

```
library(tidyverse)
library(footprint)
travel_data <- tibble(name = c("Paris->London",
                                "Paris->Amsterdam",
                                "Paris->Frankfurt"),
                       from = c("CDG", "CDG", "CDG"),
                       to = c("LHR", "AMS", "FRA"))


travel_data %>%
  rowwise() %>%
  mutate(emissions = airport_footprint(from,to,"Business","co2e"))
```

|name             |from |to  | emissions|
|:----------------|:----|:---|---------:|
|Paris->London    |CDG  |LHR |    88.531|
|Paris->Amsterdam |CDG  |AMS |   101.563|
|Paris->Frankfurt |CDG  |FRA |   114.500|
